# Checking code quality (Linting and SAST tool)
# Linting - flask8
# SAST - Bandit

name: Code Quality

on:
    #this can be called from other programme using call
    workflow_call:

jobs:
    validate:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.11", "3.12", "3.13"]

        steps:
        - name: Check out code
          uses: actions/checkout@v4

        - name: Setup python ${{ matrix.python-version }}
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install dependencies
          run:  pip install -r requirements.txt

        - name: Run linter
          run:  flake8 app.py

        - name: Run SAST
          run: bandit -r app.py
