# API Keys, sensitive data, credentials
# Gitleaks we will use to scan

name: Secrets Scan

on:
    workflow_call:

jobs:
    secrets-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0               # this will scan very code commits as well
              
            - name: Run Gitleaks Scanner
              uses: gitleaks/gitleaks-action@v2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   #this token is created by github and manages it
                GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}} # Only required for Organizations, not personal accounts.